
library(readr)
library(tidyverse)
library(ggplot2)


Braves <- read_csv("/Users/corywiard/desktop/Comp/senior-thesis/upload/BravesData2020.csv")
Brewers <- read_csv("/Users/corywiard/desktop/Comp/senior-thesis/upload/BrewersData2020.csv")
Cards <- read_csv("/Users/corywiard/desktop/Comp/senior-thesis/upload/CardsData2020.csv")
Cubs <- read_csv("/Users/corywiard/desktop/Comp/senior-thesis/upload/CubsData2020.csv")
DBacks <- read_csv("/Users/corywiard/desktop/Comp/senior-thesis/upload/DBacksData2020.csv")
Giants <- read_csv("/Users/corywiard/desktop/Comp/senior-thesis/upload/GiantsData2020.csv")
Mets <- read_csv("/Users/corywiard/desktop/Comp/senior-thesis/upload/MetsData2020.csv")
Padres <- read_csv("/Users/corywiard/desktop/Comp/senior-thesis/upload/PadresData2020.csv")
Phillies <- read_csv("/Users/corywiard/desktop/Comp/senior-thesis/upload/PhilliesData2020.csv")
Pirates <- read_csv("/Users/corywiard/desktop/Comp/senior-thesis/upload/PiratesData2020.csv")
Reds <- read_csv("/Users/corywiard/desktop/Comp/senior-thesis/upload/RedsData2020.csv")
Rockies <- read_csv("/Users/corywiard/desktop/Comp/senior-thesis/upload/RockiesData2020.csv")

par(mfrow=c(4,3))
attach(Braves)
plot(x = R, y = Wins, main="Braves Scatter plot of Wins vs Runs")
abline(lm(Wins~R), col="red")
attach(Brewers)
plot(x = R, y = Wins, main="Brewers Scatter plot of Wins vs Runs")
abline(lm(Wins~R), col="red")
attach(Cards)
plot(x = R, y = Wins, main="Cards Scatter plot of Wins vs Runs")
abline(lm(Wins~R), col="red")
attach(Cubs)
plot(x = R, y = Wins, main="Cubs Scatter plot of Wins vs Runs")
abline(lm(Wins~R), col="red")
attach(DBacks)
plot(x = R, y = Wins, main="DBacks Scatter plot of Wins vs Runs")
abline(lm(Wins~R), col="red")
attach(Giants)
plot(x = R, y = Wins, main="Giants Scatter plot of Wins vs Runs")
abline(lm(Wins~R), col="red")
attach(Mets)
plot(x = R, y = Wins, main="Mets Scatter plot of Wins vs. Runs")
abline(lm(Wins~R), col="red")
attach(Padres)
plot(x = R, y = Wins, main="Padres Scatter plot of Wins vs. Runs")
abline(lm(Wins~R), col="red")
attach(Phillies)
plot(x = R, y = Wins, main="Phillies Scatter plot of Wins vs. Runs")
abline(lm(Wins~R), col="red")
attach(Pirates)
plot(x = R, y = Wins, main="Pirates Scatter plot of Wins vs. Runs")
abline(lm(Wins~R), col="red")
attach(Reds)
plot(x = R, y = Wins, main="Reds Scatter plot of Wins vs. Runs")
abline(lm(Wins~R), col="red")
attach(Rockies)
plot(x = R, y = Wins, main="Rockies Scatter plot of Wins vs. Runs")
abline(lm(Wins~R), col="red")

par(mfrow=c(4,3))
attach(Braves)
plot(x = OBP, y = Wins, main="Braves Scatter plot of Wins vs OBP")
abline(lm(Wins~OBP), col="red")
attach(Brewers)
plot(x = OBP, y = Wins, main="Brewers Scatter plot of Wins vs OBP")
abline(lm(Wins~OBP), col="red")
attach(Cards)
plot(x = OBP, y = Wins, main="Cards Scatter plot of Wins vs OBP")
abline(lm(Wins~OBP), col="red")
attach(Cubs)
plot(x = OBP, y = Wins, main="Cubs Scatter plot of Wins vs OBP")
abline(lm(Wins~OBP), col="red")
attach(DBacks)
plot(x = OBP, y = Wins, main="DBacks Scatter plot of Wins vs OBP")
abline(lm(Wins~OBP), col="red")
attach(Giants)
plot(x = OBP, y = Wins, main="Giants Scatter plot of Wins vs OBP")
abline(lm(Wins~OBP), col="red")
attach(Mets)
plot(x = OBP, y = Wins, main="Mets Scatter plot of Wins vs. OBP")
abline(lm(Wins~OBP), col="red")
attach(Padres)
plot(x = OBP, y = Wins, main="Padres Scatter plot of Wins vs. OBP")
abline(lm(Wins~OBP), col="red")
attach(Phillies)
plot(x = OBP, y = Wins, main="Phillies Scatter plot of Wins vs. OBP")
abline(lm(Wins~OBP), col="red")
attach(Pirates)
plot(x = OBP, y = Wins, main="Pirates Scatter plot of Wins vs. OBP")
abline(lm(Wins~OBP), col="red")
attach(Reds)
plot(x = OBP, y = Wins, main="Reds Scatter plot of Wins vs. OBP")
abline(lm(Wins~OBP), col="red")
attach(Rockies)
plot(x = OBP, y = Wins, main="Rockies Scatter plot of Wins vs. OBP")
abline(lm(Wins~OBP), col="red")





par(mfrow=c(4,3))
attach(Braves)
plot(x = SB, y = Wins, main="Braves Scatter plot of Wins vs Stolen Bases")
abline(lm(Wins~SB), col="red")
attach(Brewers)
plot(x = SB, y = Wins, main="Brewers Scatter plot of Wins vs Stolen Bases")
abline(lm(Wins~SB), col="red")
attach(Cards)
plot(x = SB, y = Wins, main="Cards Scatter plot of Wins vs Stolen Bases")
abline(lm(Wins~SB), col="red")
attach(Cubs)
plot(x = SB, y = Wins, main="Cubs Scatter plot of Wins vs Stolen Bases")
abline(lm(Wins~SB), col="red")
attach(DBacks)
plot(x = SB, y = Wins, main="DBacks Scatter plot of Wins vs Stolen Bases")
abline(lm(Wins~SB), col="red")
attach(Giants)
plot(x = SB, y = Wins, main="Giants Scatter plot of Wins vs Stolen Bases")
abline(lm(Wins~SB), col="red")
attach(Mets)
plot(x = SB, y = Wins, main="Mets Scatter plot of Wins vs. Stolen Bases")
abline(lm(Wins~SB), col="red")
attach(Padres)
plot(x = SB, y = Wins, main="Padres Scatter plot of Wins vs. Stolen Bases")
abline(lm(Wins~SB), col="red")
attach(Phillies)
plot(x = SB, y = Wins, main="Phillies Scatter plot of Wins vs. Stolen Bases")
abline(lm(Wins~SB), col="red")
attach(Pirates)
plot(x = SB, y = Wins, main="Pirates Scatter plot of Wins vs. Stolen Bases")
abline(lm(Wins~SB), col="red")
attach(Reds)
plot(x = SB, y = Wins, main="Reds Scatter plot of Wins vs. Stolen Bases")
abline(lm(Wins~SB), col="red")
attach(Rockies)
plot(x = SB, y = Wins, main="Rockies Scatter plot of Wins vs. Stolen Bases")
abline(lm(Wins~SB), col="red")
